language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
  - npm run build:examples
deploy:
  - provider: pages
    github-token: $GITHUB_TOKEN
    local-dir: examples/dist
    skip-cleanup: true
    on:
      branch: master
  - provider: npm
    api_key: $NPM_TOKEN
    email: $NPM_EMAIL
    skip-cleanup: true
    on:
      tags: true