language: node_js
node_js:
  - "lts/*"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build:examples
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: examples/dist
  on:
    branch: master
